### PR TITLE
Rails 3 migration

### PR DESCRIPTION
**Pull request by danielmbarlow**
I'm sorry but it's a big PR as it includes the full migration. If you don't have a lot of time to review all the changes I suggest reviewing the few changes to the feature tests I made, and the following non-exhaustive summary of things that needed to be changed to work in Rails 3.2:
* Added binstubs
* Migrated to use Bundler
* Updated a number of gems
* Replaced some non-maintained gems and plugins in favour of built-in Rails functionality
  * bundle-fu
  * more
  * weekly_builder - replaced by jQuery calendar
  * searchlogic - replaced by Active record query interface
* ERB templates for form_for blocks changed between versions
* ActionMailer syntax changed between versions
* Annotation of models (not required, but useful in the upgrade process)
* Rails config file and asset pipeline changes
* Test changes
  * Cucumber gem now uses Capybara, so some small changes in test syntax
  * Future dates used for tests
  * Test added for reports screen
  * features/staff.feature - small change to test because of change in email_spec

### CODE REVIEW

**Comment by walter** [comment]
The PR looks good at a high level, but I want to install and run tests, etc. to have a look around.

Unfortunately I had trouble getting `therubyracer` gem to install on Mac OS X 10.11.4.

[This answer](http://stackoverflow.com/a/20145328) finally set me right.

**Comment by danielmbarlow** [comment]
Great, thanks for the feedback. Perhaps we can put a note about
therubyracer in the README. All the tests run for me on Linux, except for
one which doesn't work on Sundays. I added a TODO note to fix it. Look
forwards to hearing how the tests go.

**Comment by walter** [comment]
Yeah, another commit with a note in the README sounds good.

Looks like I still have a dependency issue. 8 of the scenarios are failing for me.

```ruby
    When I go to edit the current availability of "Gerry"                                              # features/step_definitions/web_steps.rb:18
      can't convert Symbol into Integer (ActionView::Template::Error)
      ./app/views/availabilities/_form.html.erb:44:in `[]'
      ./app/views/availabilities/_form.html.erb:44:in `block (3 levels) in _app_views_availabilities__form_html_erb___3056899252396531496_70354667549640'
      ./app/views/availabilities/_form.html.erb:40:in `each'
```

I'll take a look tomorrow. If that rings a bell, let you me know.

**Comment by danielmbarlow** [comment]
Is your availabilities.hours field being serialized in your DB as an Array?
I think the code is expecting a hash.

**Comment by walter** [comment]
> Is your availabilities.hours field being serialized in your DB as an Array?

The `Availability` object is basically empty:

```ruby
#<Availability id: nil, staff_id: nil, start_date: nil, end_date: nil, hours: \"\", admin_locked: nil, created_at: nil, updated_at: nil>
```

Adding a `.present?` strategically to `app/views/availabilities/_form.html.erb:44` allowed the tests to pass:

before -

```ruby
          <% if @availability && @availability.hours && @availability.hours[day] %>
```

after -

```ruby
          <% if @availability && @availability.hours.present? && @availability.hours[day] %>
```

**Comment by danielmbarlow** [comment]
I wonder why the availability is empty, given that the test is supposed to be editing an existing availability. Is the controller method being called in this test 'new' or 'edit'?

**Comment by walter** [comment]
Here are the scenarios that fail without the change:

```
Failing Scenarios:
cucumber features/availability.feature:12 # Scenario: Adding Availability
cucumber features/availability.feature:18 # Scenario: Adding Availability that conflicts
cucumber features/availability.feature:28 # Scenario: Adding Availability that conflicts as admin
cucumber features/availability.feature:94 # Scenario: Removing Availability
cucumber features/availability.feature:102 # Scenario: Notifying administrators of availability change
cucumber features/availability.feature:114 # Scenario: Notifying the staff member of changes to their availability
cucumber features/availability.feature:127 # Scenario: An administrator changing their own availability should send no notifications
cucumber features/availability.feature:136 # Scenario: When notification comment is empty, no emails should be sent
```

**Comment by danielmbarlow** [comment]
Ok I checked it out. It only comes up on MySQL, and I was running on Postgres. The Availability was empty because in each case the controller #new method was being run as expect. I have applied the fix you suggested, and it works fine. Thanks for the tip. I also added a note to the README. Are you happy to merge this?

**Comment by walter** [comment]
Great to hear that PG works and is an option. Didn't notice it in the `Gemfile` till now.

Almost ready to merge. Could you update the README install notes to reflect PG set up and outline how people can opt to use mysql instead if they like.

That should do it, I think.

Great work! Really appreciate it!

**Comment by danielmbarlow** [comment]
You are welcome. The feature tests were excellent at showing up bugs during the migration.

I have added a note to the README about working with MySQL or Postgres.

**Comment by walter** [comment]
https://twitter.com/wtem/status/732382004763758593

Thanks for all the great work!

http://i.giphy.com/mOOuUUIEEgq6A.gif

**Comment by danielmbarlow** [comment]
In fact - thanks for the great test suite. It has proven to be invaluable!

**Pull request merged**
